version: '3'

services:
  web:
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "80:5000"

  notification:
    deploy:
      restart_policy:
        condition: on-failure