version: '3'

services:
  db:
    image: mongo
  
  web:
    build: form
    command: python -u app.py
    ports:
    - "5000:5000"
    links:
      - db
    volumes:
      - ./form:/form
    environment:
      MONGODB_HOST: db
    
  notification:
    build: notify
    command: python -u app.py
    links:
      - db
    volumes:
      - ./notify:/notify
    environment:
      MONGODB_HOST: db
